swagger: '2.0'
info:
  title: Hello
  x-ibm-name: hello
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |-
            var apim = require('apim');
            var message = "This is a test api";
            session.output.write(message);
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
basePath: /hello
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - {}
schemes:
  - https
paths:
  /hellotest:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            type: object
      consumes: []
      produces: []
